// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Try_not_to_DIE.DBContext;

#nullable disable

namespace Try_not_to_DIE.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20241020142441_IcdDeleteTemp")]
    partial class IcdDeleteTemp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Try_not_to_DIE.Models.Comment.CommentModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsultationModelid")
                        .HasColumnType("uuid");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("authorId")
                        .HasColumnType("uuid");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("modifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("parentId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("ConsultationModelid");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Consultation.ConsultationModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InspectionModelid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("inspectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("specialityid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("InspectionModelid");

                    b.HasIndex("specialityid");

                    b.ToTable("Consultation");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Diagnosis.DiagnosisModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InspectionModelid")
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("InspectionModelid");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Doctor.DoctorModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<Guid>("specialityid")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("specialityid");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Icd10Model", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<Guid?>("parentId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("Icd10");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Inspection.InspectionModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("anamnesis")
                        .HasColumnType("text");

                    b.Property<Guid?>("baseInspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("complaints")
                        .HasColumnType("text");

                    b.Property<int>("conclusion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("deathDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("doctorid")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("nextVisitDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("patientid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("previousInspectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("treatment")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("doctorid");

                    b.HasIndex("patientid");

                    b.ToTable("Inspection");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Patient.PatientModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("createTime")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("gender")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Speciality.SpecialityModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("createTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Speciality");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Comment.CommentModel", b =>
                {
                    b.HasOne("Try_not_to_DIE.Models.Consultation.ConsultationModel", null)
                        .WithMany("comments")
                        .HasForeignKey("ConsultationModelid");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Consultation.ConsultationModel", b =>
                {
                    b.HasOne("Try_not_to_DIE.Models.Inspection.InspectionModel", null)
                        .WithMany("consultations")
                        .HasForeignKey("InspectionModelid");

                    b.HasOne("Try_not_to_DIE.Models.Speciality.SpecialityModel", "speciality")
                        .WithMany()
                        .HasForeignKey("specialityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("speciality");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Diagnosis.DiagnosisModel", b =>
                {
                    b.HasOne("Try_not_to_DIE.Models.Inspection.InspectionModel", null)
                        .WithMany("diagnoses")
                        .HasForeignKey("InspectionModelid");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Doctor.DoctorModel", b =>
                {
                    b.HasOne("Try_not_to_DIE.Models.Speciality.SpecialityModel", "speciality")
                        .WithMany()
                        .HasForeignKey("specialityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("speciality");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Inspection.InspectionModel", b =>
                {
                    b.HasOne("Try_not_to_DIE.Models.Doctor.DoctorModel", "doctor")
                        .WithMany()
                        .HasForeignKey("doctorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Try_not_to_DIE.Models.Patient.PatientModel", "patient")
                        .WithMany()
                        .HasForeignKey("patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Consultation.ConsultationModel", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("Try_not_to_DIE.Models.Inspection.InspectionModel", b =>
                {
                    b.Navigation("consultations");

                    b.Navigation("diagnoses");
                });
#pragma warning restore 612, 618
        }
    }
}
